name: Build and Deploy to main/docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: analyzer
        run: npm install

      - name: Build for production
        working-directory: analyzer
        run: npm run build

      - name: Prepare docs/analyzer
        run: |
          rm -rf docs/analyzer
          mkdir -p docs/analyzer
          cp -r analyzer/dist/* docs/analyzer/

      - name: Commit docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "ci: build and update /docs"
          git push origin main
