name: ci: build and update /docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with write access)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_PAGES }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: analyzer
        run: npm install

      - name: Build for production
        working-directory: analyzer
        run: npm run build

      - name: Prepare docs/analyzer
        run: |
          rm -rf docs/analyzer
          mkdir -p docs/analyzer
          cp -r analyzer/dist/* docs/analyzer/

      - name: Commit and push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs

          # Only commit if docs/ has changes
          if ! git diff --quiet --cached; then
            git commit -m "ci: build and update /docs"
            git push origin main
          else
            echo "No changes in docs/ to commit."
          fi
